### ISSUE TITLE
Getting error to run npx create-lwc-app conference-app command on windows 10

### ISSUE THREAD

**Issue by Sarveshgithub** [muenzpraeger/create-lwc-app#346]
I am working on trailhead module [Create the Application, trailhead module](https://trailhead.salesforce.com/en/content/learn/projects/build-your-first-app-with-lightning-web-components-open-source/create-the-application)
run command **npx create-lwc-app conference-app** on command line getting following error 
```
C:\Users\Sarvesh Kumar>npx create-lwc-app conference-app
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Kumar\AppData\Roaming\npm-cache\_npx\21828" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sarvesh Kumar\AppData\Roaming\npm-cache\_logs\2019-12-02T13_28_18_941Z-debug.log
Install for [ 'create-lwc-app@latest' ] failed with code 1
```

**Comment by muenzpraeger** [comment]
It looks like the `package.json` is missing (which it isn't). Do you get the same result when calling out the npm channel explicitly?

`npx create-lwc-app@latest conference-app`

**Comment by Sarveshgithub** [comment]
Yeah getting the same error with the above command
`npx create-lwc-app@latest conference-app`
i am using node version v10.17.0, Please see screenshot, tried with system admin as well getting the same error. Please advise
![image](https://user-images.githubusercontent.com/40709233/70030441-4186fa80-15cf-11ea-8bd5-7ee6e18be0c5.png)

**Comment by muenzpraeger** [comment]
That looks like a local issue. Can you share a screenshot of the contents of the `21980` folder on your local machine?

**Comment by Sarveshgithub** [comment]
pakage.json :
`{"metricId":"265dd65d-2abe-4081-9e8b-ec02a7212c07","metrics":{"from":"2019-03-05T05:26:45.284Z","to":"2019-11-30T17:48:51.650Z","successfulInstalls":263,"failedInstalls":6}}`
anonymous-cli-metrics.json
`{"metricId":"07fd3d84-1c43-4810-9a4d-1127f4c91570","metrics":{"from":"2019-11-30T17:51:52.304Z","to":"2019-12-03T07:46:48.062Z","successfulInstalls":4,"failedInstalls":36}}`
Folder:
![image](https://user-images.githubusercontent.com/40709233/70031460-506eac80-15d1-11ea-9110-d7aeb74879ac.png)

**Comment by muenzpraeger** [comment]
Ok, from what it looks like it's because of the whitespace in your file path (in your username to be explicit). When you look at the error message it tries to install from a partial folder, which doesn't exist.

`npm ERR! Could not install from "Kumar\AppData\Roaming\npm-cache\_npx\21828" as it does not contain a package.json file.`

That's not an issue of `create-lwc-app`, but of npm/npx, as documented for example [here](https://github.com/npm/npm/issues/20139). A potential solution, up to you to decide if you want that, could be to set the npm cache directory. There are documented solutions [here](https://github.com/zkat/npx/issues/146#issuecomment-384016791) and [here](https://github.com/zkat/npx/issues/146#issuecomment-384019497).

**Comment by muenzpraeger** [comment]
Any feedback, @Sarveshgithub, or can I close the issue?
